# Generated by Django 4.1.4 on 2022-12-17 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='messages',
            name='id',
        ),
        migrations.AddField(
            model_name='messages',
            name='uuid',
            field=models.UUIDField(default=2, primary_key=True, serialize=False, unique=True),
            preserve_default=False,
        ),
    ]
