# Generated by Django 4.1.4 on 2022-12-24 10:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0004_messageowner'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MessageOwner',
        ),
    ]
